-- Roommate profiles (discover feed)
CREATE TABLE IF NOT EXISTS roommate_profiles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  age INT NOT NULL,
  course TEXT NOT NULL,
  year TEXT NOT NULL,
  uni TEXT NOT NULL,
  budget TEXT NOT NULL,
  move_in TEXT NOT NULL,
  bio TEXT NOT NULL,
  compatibility INT NOT NULL,
  lifestyle_match INT NOT NULL,
  property_match INT NOT NULL,
  tags TEXT[] DEFAULT '{}',
  epc_grade TEXT NOT NULL,
  flood_risk TEXT NOT NULL,
  hmo_status TEXT NOT NULL,
  rent_fairness TEXT NOT NULL,
  commute_min INT NOT NULL,
  avatar TEXT NOT NULL,
  color TEXT NOT NULL,
  societies TEXT[] DEFAULT '{}',
  cleanliness INT NOT NULL,
  guests TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User session / device for anonymous likes (or link to auth later)
CREATE TABLE IF NOT EXISTS user_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Likes: one row per swipe-right (roommate or house)
CREATE TABLE IF NOT EXISTS likes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id UUID REFERENCES user_sessions(id) ON DELETE CASCADE,
  target_type TEXT NOT NULL CHECK (target_type IN ('roommate', 'house')),
  target_id TEXT NOT NULL,
  target_snapshot JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(session_id, target_type, target_id)
);

-- Indexes for core queries
CREATE INDEX IF NOT EXISTS idx_likes_session ON likes(session_id);
CREATE INDEX IF NOT EXISTS idx_likes_created ON likes(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_roommate_profiles_id ON roommate_profiles(id);

-- RLS (optional): allow read/write for anon for now; tighten with auth later
ALTER TABLE roommate_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read roommate_profiles" ON roommate_profiles FOR SELECT USING (true);
CREATE POLICY "Allow insert roommate_profiles" ON roommate_profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow read likes" ON likes FOR SELECT USING (true);
CREATE POLICY "Allow insert likes" ON likes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow read user_sessions" ON user_sessions FOR SELECT USING (true);
CREATE POLICY "Allow insert user_sessions" ON user_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update user_sessions" ON user_sessions FOR UPDATE USING (true);
